/*======================================================
    Pre-delivered content 
	Updated date: 2016.2.28
  ====================================================== */

INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (1,'现金',1,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (2,'存储卡',1,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (3,'信用卡',1,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (4,'应付账款',0,'如贷款等');
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (5,'应收账款',1,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (6,'金融账户',1,'支付宝等');
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (7,'重大资产',1,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (8,'预付款账户',2,NULL);
INSERT INTO `t_fin_account_ctgy` (`ID`,`NAME`,`ASSETFLAG`,`COMMENT`) VALUES (9,'预收款账户',3,NULL);

INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('CNY','人民币',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('EUR','欧元',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('HKD','港币',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('JPY','日币',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('TWD','新台币',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('USD','美元',NULL);
INSERT INTO `t_fin_currency` (`CURR`,`NAME`,`Symbo`) VALUES ('KRW','韩元',NULL);

INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (1,'普通收支','普通');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (2,'转账',NULL);
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (3,'货币兑换', '兑换不同的货币');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (4,'分期付款', '分期付款');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (5,'预付款', '预付款');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (6,'预收款', '预收款');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (7,'借入款', '借入款项');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (8,'借出款', '借出款项');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (9,'资产购入', '重大资产购入类');
INSERT INTO `t_fin_doc_type` (`ID`,`NAME`,`COMMENT`) VALUES (10,'资产售出', '重大资产售出类');

INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (2,'主业收入',0,NULL,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (3,'工资',0,2,'工资');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (4,'奖金',0,2,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (5,'投资类收入',0,NULL,'投资类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (6,'股票收益',0,5,'股票收益');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (7,'基金收益',0,5,'基金类收益');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (8,'利息收入',0,5,'银行利息收入');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (9,'生活类开支',1,NULL,'生活类开支');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (10,'其它收入',0,NULL,'其它收入');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (11,'物业类支出',1,9,'物业类支出');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (12,'私家车支出',1,NULL,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (13,'彩票奖金',0,10,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (14,'小区物业费',1,11,'小区的物业费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (15,'水费',1,11,'水费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (16,'电费',1,11,'电费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (17,'天然气费',1,11,'天然气费用');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (18,'物业维修费',1,11,'物业维修费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (19,'车辆保养',1,12,'保养');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (20,'汽油费',1,12,'汽车加油');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (21,'车辆保险费',1,12,'保险');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (22,'停车费',1,12,'停车费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (23,'车辆维修',1,12,'车辆维修');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (24,'其它支出',1,NULL,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (25,'保险类',1,NULL,'保险类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (26,'通讯费',1,9,'通讯费用');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (27,'固定电话/宽带',1,26,'固定电话和宽带');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (28,'手机费',1,26,'手机、流量等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (29,'彩票支出',1,24,'彩票');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (30,'人情交往类',0,NULL,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (31,'人际交往',1,NULL,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (32,'红包支出',1,31,'红包支出');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (33,'红包收入',0,30,'红包收入');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (34,'保单缴费',1,25,'保险保单缴费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (35,'津贴',0,2,'津贴类，如加班等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (36,'保险报销收入',0,5,'保险报销收入');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (37,'转账收入',0,10,'转账收入');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (38,'衣服饰品',1,9,'衣服饰品等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (39,'食品酒水',1,9,'食品酒水类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (40,'衣服鞋帽',1,38,'衣服鞋帽');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (41,'化妆饰品',1,38,'化妆品等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (42,'水果类',1,39,'水果');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (43,'零食类',1,39,'零食类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (44,'烟酒茶类',1,39,'烟酒茶等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (45,'咖啡外卖类',1,39,'咖啡与快餐');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (46,'早中晚餐',1,39,'正餐类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (47,'请客送礼',1,31,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (48,'孝敬家长',1,31,NULL);
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (49,'休闲娱乐',1,9,'休闲娱乐类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (50,'旅游度假',1,49,'旅游度假');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (51,'电影演出',1,49,'看电影，看演出等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (52,'摄影外拍类',1,49,'摄影外拍');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (53,'腐败聚会类',1,49,'KTV之类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (54,'学习进修',1,9,'学习进修');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (55,'银行利息',1,25,'银行利息');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (56,'银行手续费',1,25,'银行手续费');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (57,'违章付款类',1,12,'违章付款等');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (58,'书刊杂志',1,54,'书刊和杂志');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (59,'培训进修',1,54,'培训进修类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (60,'转账支出',1,24,'转账');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (61,'日常用品',1,9,'日常用品');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (62,'日用品',1,61,'日用品类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (63,'电子产品类',1,61,'电子产品类');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (64,'厨房用具',1,61,'厨房用具');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (65,'洗涤用品',1,61,'洗涤用品');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (66,'大家电类',1,61,'大家电');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (67,'保健护理用品',1,61,'保健护理');
INSERT INTO `t_fin_tran_type` (`ID`,`NAME`,`EXPENSE`,`PARID`,`COMMENT`) VALUES (68,'喂哺用品',1,61,NULL);

INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (1,NULL,'语文','语文');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (2,1,'诗词','唐诗宋词等');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (3,1,'识字','拼音认读和笔画等');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (4,1,'文言文','文言文等');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (5,1,'古典名著','古典名著等');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (6,NULL,'数学','数学类');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (7,6,'算术','加减法');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (8,6,'代数','代数');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (9,6,'几何','几何类');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (10,NULL,'英语','英语类');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (11,10,'词汇','英语词汇');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (12,10,'语法','英语语法');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (13,NULL,'日语','日语类');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (14,13,'词汇','日语词汇');
INSERT INTO `t_learn_ctg` (`ID`,`PARENT_ID`,`NAME`,`COMMENT`) VALUES (15,13,'语法','日语语法');

INSERT INTO `t_fin_setting` (`SETID`,`SETVALUE`,`COMMENT`) VALUES ('LocalCurrency','CNY','本币');
INSERT INTO `t_fin_setting` (`SETID`,`SETVALUE`,`COMMENT`) VALUES ('CurryExgToilence','2','货币兑换容错');

INSERT INTO `t_language` (`LANG`,`NAME`,`NAVNAME`) VALUES ('EN','English', 'English');
INSERT INTO `t_language` (`LANG`,`NAME`,`NAVNAME`) VALUES ('ZH','Simp. Chinese', '简体中文');
INSERT INTO `t_language` (`LANG`,`NAME`,`NAVNAME`) VALUES ('TW','Trad. Chinese', '繁體中文');
INSERT INTO `t_language` (`LANG`,`NAME`,`NAVNAME`) VALUES ('JP','Japanese', '日本語');

INSERT INTO `t_lib_setting` (`SETNAME`, `SETDESP`, `SETVALUE`) VALUES ('BOOKAUTHOR', 'Tags for Authors in Book', '["Writer"]');
INSERT INTO `t_lib_setting` (`SETNAME`, `SETDESP`, `SETVALUE`) VALUES ('BOOKPRESS', 'Tags for Presses in Book', '["Press"]');

INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 1, '小说', '小说类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 2, '悬疑推理类', '悬疑推理类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 3, '言情类', '言情类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 4, '恐怖惊悚类', '恐怖惊悚类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 5, '官场类', '官场类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 6, '武侠类', '武侠类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 7, '科幻类', '科幻类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 8, '历史类', '历史类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 9, '社会类', '社会类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 10, '职场类', '职场类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 11, '奇幻玄幻类', '奇幻玄幻类小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 13, '中国古典小说类', '中国古典小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 14, '世界名著类', '世界名著类', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 15, '古典小说类', '古典小说', 1 );
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 21, '文学', '文学类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 22, '散文/随笔/书信', '散文/随笔/书信', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 23, '诗歌词曲', '诗歌和词曲', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 24, '中国文学', '中国文学', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 25, '外国文学', '外国文学', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 26, '纪实文学', '纪实文学类', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 27, '文学理论和文学史', '文学理论和文学史', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 28, '校园青春文学', '校园文学和青春文学', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 29, '儿童文学', '认同文学类', 21);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 41, '艺术类', '艺术类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 42, '绘画', '绘画类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 43, '摄影', '摄影类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 44, '书法与篆刻', '书法与篆刻类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 45, '艺术理论与艺术史', '艺术理论与历史类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 46, '建筑', '建筑', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 47, '戏剧', '戏剧类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 48, '舞蹈', '舞蹈类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 49, '音乐', '音乐类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 50, '其他艺术', '其他艺术类', 41);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 61, '励志与成功类', '励志与成功类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 62, '演讲与口才', '演讲与口才类', 61);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 63, '人际与社交', '人际与社交类', 61);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 64, '心灵鸡汤', '心灵鸡汤类', 61);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 71, '经济与管理', '经济与管理类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 72, '经济学理论', '经济学理论类', 71);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 73, '会计与审计', '会计与审计类', 71);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 74, '管理学理论', '管理学理论类', 71);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 75, '金融证券类', '金融与证券类', 71);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 81, '旅游与地图', '旅游与地图类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 82, '烹饪与美食', '烹饪与美食类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 83, '时尚与美妆', '时尚与美妆类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 84, '家居与装修', '家居与装修类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 85, '健身与保健', '健身与保健类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 86, '漫画', '漫画类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 87, '历史', '历史类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 88, '政治与军事', '政治与军事类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 89, '法律', '法律类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 91, '教材与工具书', '教材与工具书类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 92, '小学教材', '小学教材类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 93, '初中教材', '初中教材类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 94, '高中教材', '高中教材类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 95, '大学教材', '大学教材类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 96, '考试教材', '考试教材类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 97, '工具书', '工具书类', 91);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 101, '计算机与互联网', '计算机与互联网类', NULL);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 102, '编程语言与程序设计', '编程语言与程序设计类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 103, '软件工程', '软件工程类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 104, '数据库', '数据库类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 105, '操作系统', '操作系统类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 106, '网络与通信', '网络与通信类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 107, '图形图像与视频', '图形图像与视频类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 108, '办公软件', '办公软件类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 109, '计算机理论', '计算机理论类', 101);
INSERT INTO `t_lib_booktype` (`ID`, `NAME`, `OTHERS`, `PARID`) VALUES ( 110, 'ERP软件', 'ERP软件类', 101);

INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 1, 0 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 0 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 1 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 2 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 4 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 7 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 15 );
INSERT INTO `t_learn_recurtypedates` (`ID`, `DEFDAYS`) VALUES ( 2, 30 );

INSERT INTO `t_module` (`MODULE`, `NAME`) VALUES ( 'USR', 'User registeration' );
INSERT INTO `t_module` (`MODULE`, `NAME`) VALUES ( 'LRN', 'Learning Trace' );
INSERT INTO `t_module` (`MODULE`, `NAME`) VALUES ( 'FIN', 'Finance Trace' );
INSERT INTO `t_module` (`MODULE`, `NAME`) VALUES ( 'LIB', 'Library' );

INSERT INTO `t_user_prof` (`USERID`, `MODULE`, `READFLAG`, `CREATEFLAG`, `UPDATEFLAG`, `FULLCTRLFLAG`) VALUES ( '', 'USR', 1, 1, 0, 0 );
INSERT INTO `t_user_prof` (`USERID`, `MODULE`, `READFLAG`, `CREATEFLAG`, `UPDATEFLAG`, `FULLCTRLFLAG`) VALUES ( '', 'LRN', 1, 1, 0, 0 );
INSERT INTO `t_user_prof` (`USERID`, `MODULE`, `READFLAG`, `CREATEFLAG`, `UPDATEFLAG`, `FULLCTRLFLAG`) VALUES ( '', 'FIN', 0, 0, 0, 0 );
INSERT INTO `t_user_prof` (`USERID`, `MODULE`, `READFLAG`, `CREATEFLAG`, `UPDATEFLAG`, `FULLCTRLFLAG`) VALUES ( '', 'LIB', 1, 1, 0, 0 );

